FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.3

# File Author / Maintainer.
LABEL maintainer="Leandro Cassiano <lcassian@akamai.com>"

# Add your logstash plugins setup here
RUN bin/logstash-plugin install logstash-output-mqtt